import 'package:flutter/material.dart';
import 'package:flutter/src/foundation/key.dart';
import 'package:flutter/src/widgets/framework.dart';
import 'package:html/parser.dart' as htmlparser;
import 'package:html/dom.dart' as dom;
import 'package:flutter_html/flutter_html.dart';

class TermsScreen extends StatefulWidget {
  const TermsScreen({Key? key}) : super(key: key);

  @override
  State<TermsScreen> createState() => _TermsScreenState();
}

class _TermsScreenState extends State<TermsScreen> {
  var htmlData = r"""
<h1 style="text-align:center"><span style="font-size:24pt"><span style="font-family:&quot;Times New Roman&quot;,serif"><strong><span style="color:black">Terms &amp; Conditions</span></strong></span></span></h1>

<p style="text-align:center"><span style="font-size:12pt"><span style="font-family:&quot;Times New Roman&quot;,serif">Updated at April 19th, 2023</span></span></p>


<h2><span style="font-size:18pt"><span style="font-family:&quot;Times New Roman&quot;,serif"><strong>General Terms</strong></span></span></h2>

<p><span style="font-size:12pt"><span style="font-family:&quot;Times New Roman&quot;,serif">By accessing and placing an order with National Aero Stands, you confirm that you are in agreement with and bound by the terms of service contained in the Terms &amp; Conditions outlined below. These terms apply to the entire website and any email or other type of communication between you and National Aero Stands.</span></span></p>


<p><span style="font-size:12pt"><span style="font-family:&quot;Times New Roman&quot;,serif">Under no circumstances shall National Aero Stands team be liable for any direct, indirect, special, incidental or consequential damages, including, but not limited to, loss of data or profit, arising out of the use, or the inability to use, the materials on this site, even if National Aero Stands team or an authorized representative has been advised of the possibility of such damages. If your use of materials from this site results in the need for servicing, repair or correction of equipment or data, you assume any costs thereof.</span></span></p>


<p><span style="font-size:12pt"><span style="font-family:&quot;Times New Roman&quot;,serif">National Aero Stands will not be responsible for any outcome that may occur during the course of usage of our resources. We reserve the rights to change prices and revise the resources usage policy in any moment.</span></span></p>


<h2><span style="font-size:18pt"><span style="font-family:&quot;Times New Roman&quot;,serif"><strong>License</strong></span></span></h2>

<p><span style="font-size:12pt"><span style="font-family:&quot;Times New Roman&quot;,serif">National Aero Stands grants you a revocable, non-exclusive, non-transferable, limited license to download, install and use the website/app strictly in accordance with the terms of this Agreement.</span></span></p>


<p><span style="font-size:12pt"><span style="font-family:&quot;Times New Roman&quot;,serif">These Terms &amp; Conditions are a contract between you and National Aero Stands (referred to in these Terms &amp; Conditions as &quot;National Aero Stands&quot;, &quot;us&quot;, &quot;we&quot; or &quot;our&quot;), the provider of the National Aero Stands website and the services accessible from the National Aero Stands website (which are collectively referred to in these Terms &amp; Conditions as the &quot;National Aero Stands Service&quot;).</span></span></p>


<p><span style="font-size:12pt"><span style="font-family:&quot;Times New Roman&quot;,serif">You are agreeing to be bound by these Terms &amp; Conditions. If you do not agree to these Terms &amp; Conditions, please do not use the National Aero Stands Service. In these Terms &amp; Conditions, &quot;you&quot; refers both to you as an individual and to the entity you represent. If you violate any of these Terms &amp; Conditions, we reserve the right to cancel your account or block access to your account without notice.</span></span></p>


<h2><span style="font-size:18pt"><span style="font-family:&quot;Times New Roman&quot;,serif"><strong>Definitions and key terms</strong></span></span></h2>

<p><span style="font-size:12pt"><span style="font-family:&quot;Times New Roman&quot;,serif">To help explain things as clearly as possible in this Terms &amp; Conditions, every time any of these terms are referenced, are strictly defined as:</span></span></p>


<ul>
	<li><span style="font-size:12pt"><span style="font-family:&quot;Times New Roman&quot;,serif">Cookie:&Acirc;&nbsp;small amount of data generated by a website and saved by your web browser. It is used to identify your browser, provide analytics, remember information about you such as your language preference or login information.</span></span></li>
	<li><span style="font-size:12pt"><span style="font-family:&quot;Times New Roman&quot;,serif">Company: when this terms mention &acirc;&euro;&oelig;Company,&acirc;&euro; &acirc;&euro;&oelig;we,&acirc;&euro; &acirc;&euro;&oelig;us,&acirc;&euro; or &acirc;&euro;&oelig;our,&acirc;&euro; it refers to https://stands.aero/, (1449 Airpark Horseshoe Bay, Texas 78657), that is responsible for your information under this Terms &amp; Conditions.</span></span></li>
	<li><span style="font-size:12pt"><span style="font-family:&quot;Times New Roman&quot;,serif">Country: where National Aero Stands or the owners/founders of National Aero Stands are based, in this case is United States</span></span></li>
	<li><span style="font-size:12pt"><span style="font-family:&quot;Times New Roman&quot;,serif">Device:&Acirc;&nbsp;any internet connected device such as a phone, tablet, computer or any other device that can be used to visit National Aero Stands and use the services.</span></span></li>
	<li><span style="font-size:12pt"><span style="font-family:&quot;Times New Roman&quot;,serif">Service: refers to the service provided by National Aero Stands as described in the relative terms (if available) and on this platform.</span></span></li>
	<li><span style="font-size:12pt"><span style="font-family:&quot;Times New Roman&quot;,serif">Third-party service:&Acirc;&nbsp;refers to advertisers, contest sponsors, promotional and marketing partners, and others who provide our content or whose products or services we think may interest you.</span></span></li>
	<li><span style="font-size:12pt"><span style="font-family:&quot;Times New Roman&quot;,serif">You: a person or entity that is registered with National Aero Stands to use the Services.</span></span></li>
</ul>


<h2><span style="font-size:18pt"><span style="font-family:&quot;Times New Roman&quot;,serif"><strong>Restrictions</strong></span></span></h2>

<p><span style="font-size:12pt"><span style="font-family:&quot;Times New Roman&quot;,serif">You agree not to, and you will not permit others to:</span></span></p>


<ul>
	<li><span style="font-size:12pt"><span style="font-family:&quot;Times New Roman&quot;,serif">License, sell, rent, lease, assign, distribute, transmit, host, outsource, disclose or otherwise commercially exploit the website/app or make the platform available to any third party.</span></span></li>
	<li><span style="font-size:12pt"><span style="font-family:&quot;Times New Roman&quot;,serif">Modify, make derivative works of, disassemble, decrypt, reverse compile or reverse engineer any part of the website/app.</span></span></li>
	<li><span style="font-size:12pt"><span style="font-family:&quot;Times New Roman&quot;,serif">Remove, alter or obscure any proprietary notice (including any notice of copyright or trademark) of National Aero Stands or its affiliates, partners, suppliers or the licensors of the website/app.</span></span></li>
</ul>


<h2><span style="font-size:18pt"><span style="font-family:&quot;Times New Roman&quot;,serif"><strong>Return and Refund Policy</strong></span></span></h2>

<p><span style="font-size:12pt"><span style="font-family:&quot;Times New Roman&quot;,serif">Thanks for shopping at National Aero Stands. We appreciate the fact that you like to buy the stuff we build. We also want to make sure you have a rewarding experience while you&acirc;&euro;&trade;re exploring, evaluating, and purchasing our products.</span></span></p>


<p><span style="font-size:12pt"><span style="font-family:&quot;Times New Roman&quot;,serif">As with any shopping experience, there are terms and conditions that apply to transactions at National Aero Stands. We&acirc;&euro;&trade;ll be as brief as our attorneys will allow. The main thing to remember is that by placing an order or making a purchase at National Aero Stands, you agree to the terms along with National Aero Stands&acirc;&euro;&trade;s&Acirc;&nbsp;Privacy Policy.</span></span></p>


<p><span style="font-size:12pt"><span style="font-family:&quot;Times New Roman&quot;,serif">If, for any reason, You are not completely satisfied with any good or service that we provide, don&#39;t hesitate to contact us and we will discuss any of the issues you are going through with our product.</span></span></p>


<h2><span style="font-size:18pt"><span style="font-family:&quot;Times New Roman&quot;,serif"><strong>Your Suggestions</strong></span></span></h2>

<p><span style="font-size:12pt"><span style="font-family:&quot;Times New Roman&quot;,serif">Any feedback, comments, ideas, improvements or suggestions (collectively, &quot;Suggestions&quot;) provided by you to National Aero Stands with respect to the website/app shall remain the sole and exclusive property of National Aero Stands.</span></span></p>


<p><span style="font-size:12pt"><span style="font-family:&quot;Times New Roman&quot;,serif">National Aero Stands shall be free to use, copy, modify, publish, or redistribute the Suggestions for any purpose and in any way without any credit or any compensation to you.</span></span></p>


<h2><span style="font-size:18pt"><span style="font-family:&quot;Times New Roman&quot;,serif"><strong>Your Consent</strong></span></span></h2>

<p><span style="font-size:12pt"><span style="font-family:&quot;Times New Roman&quot;,serif">We&#39;ve updated our&Acirc;&nbsp;Terms &amp; Conditions&Acirc;&nbsp;to provide you with complete transparency into what is being set when you visit our site and how it&#39;s being used. By using our website/app, registering an account, or making a purchase, you hereby consent to our Terms &amp; Conditions.</span></span></p>


<h2><span style="font-size:18pt"><span style="font-family:&quot;Times New Roman&quot;,serif"><strong>Links to Other Websites</strong></span></span></h2>

<p><span style="font-size:12pt"><span style="font-family:&quot;Times New Roman&quot;,serif">This Terms &amp; Conditions applies only to the Services. The Services may contain links to other websites not operated or controlled by National Aero Stands. We are not responsible for the content, accuracy or opinions expressed in such websites, and such websites are not investigated, monitored or checked for accuracy or completeness by us. Please remember that when you use a link to go from the Services to another website, our Terms &amp; Conditions are no longer in effect. Your browsing and interaction on any other website, including those that have a link on our platform, is subject to that website&acirc;&euro;&trade;s own rules and policies. Such third parties may use their own cookies or other methods to collect information about you.</span></span></p>


<h2><span style="font-size:18pt"><span style="font-family:&quot;Times New Roman&quot;,serif"><strong>Cookies</strong></span></span></h2>

<p><span style="font-size:12pt"><span style="font-family:&quot;Times New Roman&quot;,serif">National Aero Stands uses &quot;Cookies&quot; to identify the areas of our website/app that you have visited. A Cookie is a small piece of data stored on your computer or mobile device by your web browser. We use Cookies to enhance the performance and functionality of our website/app but are non-essential to their use. However, without these cookies, certain functionality like videos may become unavailable or you would be required to enter your login details every time you visit the website/app as we would not be able to remember that you had logged in previously. Most web browsers can be set to disable the use of Cookies. However, if you disable Cookies, you may not be able to access functionality on our website/app correctly or at all. We never place Personally Identifiable Information in Cookies.</span></span></p>


<h2><span style="font-size:18pt"><span style="font-family:&quot;Times New Roman&quot;,serif"><strong>Changes To Our Terms &amp; Conditions</strong></span></span></h2>

<p><span style="font-size:12pt"><span style="font-family:&quot;Times New Roman&quot;,serif">You acknowledge and agree that National Aero Stands may stop (permanently or temporarily) providing the Service (or any features within the Service) to you or to users generally at National Aero Stands&acirc;&euro;&trade;s sole discretion, without prior notice to you. You may stop using the Service at any time. You do not need to specifically inform National Aero Stands when you stop using the Service. You acknowledge and agree that if National Aero Stands disables access to your account, you may be prevented from accessing the Service, your account details or any files or other materials which is contained in your account.</span></span></p>


<p><span style="font-size:12pt"><span style="font-family:&quot;Times New Roman&quot;,serif">If we decide to change our Terms &amp; Conditions, we will post those changes on this page, and/or update the Terms &amp; Conditions modification date below.</span></span></p>


<h2><span style="font-size:18pt"><span style="font-family:&quot;Times New Roman&quot;,serif"><strong>Modifications to Our website/app</strong></span></span></h2>

<p><span style="font-size:12pt"><span style="font-family:&quot;Times New Roman&quot;,serif">National Aero Stands reserves the right to modify, suspend or discontinue, temporarily or permanently, the website/app or any service to which it connects, with or without notice and without liability to you.</span></span></p>


<h2><span style="font-size:18pt"><span style="font-family:&quot;Times New Roman&quot;,serif"><strong>Updates to Our website/app</strong></span></span></h2>

<p><span style="font-size:12pt"><span style="font-family:&quot;Times New Roman&quot;,serif">National Aero Stands may from time to time provide enhancements or improvements to the features/ functionality of the website/app, which may include patches, bug fixes, updates, upgrades and other modifications (&quot;Updates&quot;).</span></span></p>


<p><span style="font-size:12pt"><span style="font-family:&quot;Times New Roman&quot;,serif">Updates may modify or delete certain features and/or functionalities of the website/app. You agree that National Aero Stands has no obligation to (i) provide any Updates, or (ii) continue to provide or enable any particular features and/or functionalities of the website/app to you.</span></span></p>


<p><span style="font-size:12pt"><span style="font-family:&quot;Times New Roman&quot;,serif">You further agree that all Updates will be (i) deemed to constitute an integral part of the website/app, and (ii) subject to the terms and conditions of this Agreement.</span></span></p>


<h2><span style="font-size:18pt"><span style="font-family:&quot;Times New Roman&quot;,serif"><strong>Third-Party Services</strong></span></span></h2>

<p><span style="font-size:12pt"><span style="font-family:&quot;Times New Roman&quot;,serif">We may display, include or make available third-party content (including data, information, applications and other products services) or provide links to third-party websites or services (&quot;Third- Party Services&quot;).</span></span></p>


<p><span style="font-size:12pt"><span style="font-family:&quot;Times New Roman&quot;,serif">You acknowledge and agree that National Aero Stands shall not be responsible for any Third-Party Services, including their accuracy, completeness, timeliness, validity, copyright compliance, legality, decency, quality or any other aspect thereof. National Aero Stands does not assume and shall not have any liability or responsibility to you or any other person or entity for any Third-Party Services.</span></span></p>


<p><span style="font-size:12pt"><span style="font-family:&quot;Times New Roman&quot;,serif">Third-Party Services and links thereto are provided solely as a convenience to you and you access and use them entirely at your own risk and subject to such third parties&#39; terms and conditions.</span></span></p>


<h2><span style="font-size:18pt"><span style="font-family:&quot;Times New Roman&quot;,serif"><strong>Term and Termination</strong></span></span></h2>

<p><span style="font-size:12pt"><span style="font-family:&quot;Times New Roman&quot;,serif">This Agreement shall remain in effect until terminated by you or National Aero Stands.</span></span></p>


<p><span style="font-size:12pt"><span style="font-family:&quot;Times New Roman&quot;,serif">National Aero Stands may, in its sole discretion, at any time and for any or no reason, suspend or terminate this Agreement with or without prior notice.</span></span></p>


<p><span style="font-size:12pt"><span style="font-family:&quot;Times New Roman&quot;,serif">This Agreement will terminate immediately, without prior notice from National Aero Stands, in the event that you fail to comply with any provision of this Agreement. You may also terminate this Agreement by deleting the website/app and all copies thereof from your computer.</span></span></p>


<p><span style="font-size:12pt"><span style="font-family:&quot;Times New Roman&quot;,serif">Upon termination of this Agreement, you shall cease all use of the website/app and delete all copies of the website/app from your computer.</span></span></p>


<p><span style="font-size:12pt"><span style="font-family:&quot;Times New Roman&quot;,serif">Termination of this Agreement will not limit any of National Aero Stands&#39;s rights or remedies at law or in equity in case of breach by you (during the term of this Agreement) of any of your obligations under the present Agreement.</span></span></p>


<h2><span style="font-size:18pt"><span style="font-family:&quot;Times New Roman&quot;,serif"><strong>Copyright Infringement Notice</strong></span></span></h2>

<p><span style="font-size:12pt"><span style="font-family:&quot;Times New Roman&quot;,serif">If you are a copyright owner or such owner&acirc;&euro;&trade;s agent and believe any material on our website/app constitutes an infringement on your copyright, please contact us setting forth the following information: (a) a physical or electronic signature of the copyright owner or a person authorized to act on his behalf; (b) identification of the material that is claimed to be infringing; (c) your contact information, including your address, telephone number, and an email; (d) a statement by you that you have a good faith belief that use of the material is not authorized by the copyright owners; and (e) the a statement that the information in the notification is accurate, and, under penalty of perjury you are authorized to act on behalf of the owner.</span></span></p>


<h2><span style="font-size:18pt"><span style="font-family:&quot;Times New Roman&quot;,serif"><strong>Indemnification</strong></span></span></h2>

<p><span style="font-size:12pt"><span style="font-family:&quot;Times New Roman&quot;,serif">You agree to indemnify and hold National Aero Stands and its parents, subsidiaries, affiliates, officers, employees, agents, partners and licensors (if any) harmless from any claim or demand, including reasonable attorneys&#39; fees, due to or arising out of your: (a) use of the website/app; (b) violation of this Agreement or any law or regulation; or (c) violation of any right of a third party.</span></span></p>


<h2><span style="font-size:18pt"><span style="font-family:&quot;Times New Roman&quot;,serif"><strong>No Warranties</strong></span></span></h2>

<p><span style="font-size:12pt"><span style="font-family:&quot;Times New Roman&quot;,serif">The website/app is provided to you &quot;AS IS&quot; and &quot;AS AVAILABLE&quot; and with all faults and defects without warranty of any kind. To the maximum extent permitted under applicable law, National Aero Stands, on its own behalf and on behalf of its affiliates and its and their respective licensors and service providers, expressly disclaims all warranties, whether express, implied, statutory or otherwise, with respect to the website/app, including all implied warranties of merchantability, fitness for a particular purpose, title and non-infringement, and warranties that may arise out of course of dealing, course of performance, usage or trade practice. Without limitation to the foregoing, National Aero Stands provides no warranty or undertaking, and makes no representation of any kind that the website/app will meet your requirements, achieve any intended results, be compatible or work with any other software, website/apps, systems or services, operate without interruption, meet any performance or reliability standards or be error free or that any errors or defects can or will be corrected.</span></span></p>


<p><span style="font-size:12pt"><span style="font-family:&quot;Times New Roman&quot;,serif">Without limiting the foregoing, neither National Aero Stands nor any National Aero Stands&#39;s provider makes any representation or warranty of any kind, express or implied: (i) as to the operation or availability of the website/app, or the information, content, and materials or products included thereon; (ii) that the website/app will be uninterrupted or error-free; (iii) as to the accuracy, reliability, or currency of any information or content provided through the website/app; or (iv) that the website/app, its servers, the content, or e-mails sent from or on behalf of National Aero Stands are free of viruses, scripts, trojan horses, worms, malware, timebombs or other harmful components.</span></span></p>


<p><span style="font-size:12pt"><span style="font-family:&quot;Times New Roman&quot;,serif">Some jurisdictions do not allow the exclusion of or limitations on implied warranties or the limitations on the applicable statutory rights of a consumer, so some or all of the above exclusions and limitations may not apply to you.</span></span></p>


<h2><span style="font-size:18pt"><span style="font-family:&quot;Times New Roman&quot;,serif"><strong>Limitation of Liability</strong></span></span></h2>

<p><span style="font-size:12pt"><span style="font-family:&quot;Times New Roman&quot;,serif">Notwithstanding any damages that you might incur, the entire liability of National Aero Stands and any of its suppliers under any provision of this Agreement and your exclusive remedy for all of the foregoing shall be limited to the amount actually paid by you for the website/app.</span></span></p>


<p><span style="font-size:12pt"><span style="font-family:&quot;Times New Roman&quot;,serif">To the maximum extent permitted by applicable law, in no event shall National Aero Stands or its suppliers be liable for any special, incidental, indirect, or consequential damages whatsoever (including, but not limited to, damages for loss of profits, for loss of data or other information, for business interruption, for personal injury, for loss of privacy arising out of or in any way related to the use of or inability to use the website/app, third-party software and/or third-party hardware used with the website/app, or otherwise in connection with any provision of this Agreement), even if National Aero Stands or any supplier has been advised of the possibility of such damages and even if the remedy fails of its essential purpose.</span></span></p>


<p><span style="font-size:12pt"><span style="font-family:&quot;Times New Roman&quot;,serif">Some states/jurisdictions do not allow the exclusion or limitation of incidental or consequential damages, so the above limitation or exclusion may not apply to you.</span></span></p>


<h2><span style="font-size:18pt"><span style="font-family:&quot;Times New Roman&quot;,serif"><strong>Severability</strong></span></span></h2>

<p><span style="font-size:12pt"><span style="font-family:&quot;Times New Roman&quot;,serif">If any provision of this Agreement is held to be unenforceable or invalid, such provision will be changed and interpreted to accomplish the objectives of such provision to the greatest extent possible under applicable law and the remaining provisions will continue in full force and effect.</span></span></p>


<p><span style="font-size:12pt"><span style="font-family:&quot;Times New Roman&quot;,serif">This Agreement, together with the Privacy Policy and any other legal notices published by National Aero Stands on the Services, shall constitute the entire agreement between you and National Aero Stands concerning the Services. If any provision of this Agreement is deemed invalid by a court of competent jurisdiction, the invalidity of such provision shall not affect the validity of the remaining provisions of this Agreement, which shall remain in full force and effect. No waiver of any term of this Agreement shall be deemed a further or continuing waiver of such term or any other term, and National Aero Stands&acirc;&euro;&trade;s failure to assert any right or provision under this Agreement shall not constitute a waiver of such right or provision. YOU AND National Aero Stands AGREE THAT ANY CAUSE OF ACTION ARISING OUT OF OR RELATED TO THE SERVICES MUST COMMENCE WITHIN ONE (1) YEAR AFTER THE CAUSE OF ACTION ACCRUES. OTHERWISE, SUCH CAUSE OF ACTION IS PERMANENTLY BARRED.</span></span></p>


<h2><span style="font-size:18pt"><span style="font-family:&quot;Times New Roman&quot;,serif"><strong>Waiver</strong></span></span></h2>

<p><span style="font-size:12pt"><span style="font-family:&quot;Times New Roman&quot;,serif">Except as provided herein, the failure to exercise a right or to require performance of an obligation under this Agreement shall not effect a party&#39;s ability to exercise such right or require such performance at any time thereafter nor shall be the waiver of a breach constitute waiver of any subsequent breach.</span></span></p>


<p><span style="font-size:12pt"><span style="font-family:&quot;Times New Roman&quot;,serif">No failure to exercise, and no delay in exercising, on the part of either party, any right or any power under this Agreement shall operate as a waiver of that right or power. Nor shall any single or partial exercise of any right or power under this Agreement preclude further exercise of that or any other right granted herein. In the event of a conflict between this Agreement and any applicable purchase or other terms, the terms of this Agreement shall govern.</span></span></p>


<h2><span style="font-size:18pt"><span style="font-family:&quot;Times New Roman&quot;,serif"><strong>Amendments to this Agreement</strong></span></span></h2>

<p><span style="font-size:12pt"><span style="font-family:&quot;Times New Roman&quot;,serif">National Aero Stands reserves the right, at its sole discretion, to modify or replace this Agreement at any time. If a revision is material we will provide at least 30 days&#39; notice prior to any new terms taking effect. What constitutes a material change will be determined at our sole discretion.</span></span></p>


<p><span style="font-size:12pt"><span style="font-family:&quot;Times New Roman&quot;,serif">By continuing to access or use our website/app after any revisions become effective, you agree to be bound by the revised terms. If you do not agree to the new terms, you are no longer authorized to use National Aero Stands.</span></span></p>


<h2><span style="font-size:18pt"><span style="font-family:&quot;Times New Roman&quot;,serif"><strong>Entire Agreement</strong></span></span></h2>

<p><span style="font-size:12pt"><span style="font-family:&quot;Times New Roman&quot;,serif">The Agreement constitutes the entire agreement between you and National Aero Stands regarding your use of the website/app and supersedes all prior and contemporaneous written or oral agreements between you and National Aero Stands.</span></span></p>


<p><span style="font-size:12pt"><span style="font-family:&quot;Times New Roman&quot;,serif">You may be subject to additional terms and conditions that apply when you use or purchase other National Aero Stands&#39;s services, which National Aero Stands will provide to you at the time of such use or purchase.</span></span></p>


<h2><span style="font-size:18pt"><span style="font-family:&quot;Times New Roman&quot;,serif"><strong>Updates to Our Terms</strong></span></span></h2>

<p><span style="font-size:12pt"><span style="font-family:&quot;Times New Roman&quot;,serif">We may change our Service and policies, and we may need to make changes to these Terms so that they accurately reflect our Service and policies. Unless otherwise required by law, we will notify you (for example, through our Service) before we make changes to these Terms and give you an opportunity to review them before they go into effect. Then, if you continue to use the Service, you will be bound by the updated Terms. If you do not want to agree to these or any updated Terms, you can delete your account.</span></span></p>


<h2><span style="font-size:18pt"><span style="font-family:&quot;Times New Roman&quot;,serif"><strong>Intellectual Property</strong></span></span></h2>

<p><span style="font-size:12pt"><span style="font-family:&quot;Times New Roman&quot;,serif">The website/app and its entire contents, features and functionality (including but not limited to all information, software, text, displays, images, video and audio, and the design, selection and arrangement thereof), are owned by National Aero Stands, its licensors or other providers of such material and are protected by United States and international copyright, trademark, patent, trade secret and other intellectual property or proprietary rights laws. The material may not be copied, modified, reproduced, downloaded or distributed in any way, in whole or in part, without the express prior written permission of National Aero Stands, unless and except as is expressly provided in these Terms &amp; Conditions. Any unauthorized use of the material is prohibited.</span></span></p>


<h2><span style="font-size:18pt"><span style="font-family:&quot;Times New Roman&quot;,serif"><strong>Agreement to Arbitrate</strong></span></span></h2>

<p><span style="font-size:12pt"><span style="font-family:&quot;Times New Roman&quot;,serif">This section applies to any dispute EXCEPT IT DOESN&acirc;&euro;&trade;T INCLUDE A DISPUTE RELATING TO CLAIMS FOR INJUNCTIVE OR EQUITABLE RELIEF REGARDING THE ENFORCEMENT OR VALIDITY OF YOUR OR National Aero Stands&acirc;&euro;&trade;s INTELLECTUAL PROPERTY RIGHTS. The term &acirc;&euro;&oelig;dispute&acirc;&euro; means any dispute, action, or other controversy between you and National Aero Stands concerning the Services or this agreement, whether in contract, warranty, tort, statute, regulation, ordinance, or any other legal or equitable basis. &acirc;&euro;&oelig;Dispute&acirc;&euro; will be given the broadest possible meaning allowable under law.</span></span></p>


<h2><span style="font-size:18pt"><span style="font-family:&quot;Times New Roman&quot;,serif"><strong>Notice of Dispute</strong></span></span></h2>

<p><span style="font-size:12pt"><span style="font-family:&quot;Times New Roman&quot;,serif">In the event of a dispute, you or National Aero Stands must give the other a Notice of Dispute, which is a written statement that sets forth the name, address, and contact information of the party giving it, the facts giving rise to the dispute, and the relief requested. You must send any Notice of Dispute via email to:&Acirc;&nbsp;<a href=""></a>. National Aero Stands will send any Notice of Dispute to you by mail to your address if we have it, or otherwise to your email address. You and National Aero Stands will attempt to resolve any dispute through informal negotiation within sixty (60) days from the date the Notice of Dispute is sent. After sixty (60) days, you or National Aero Stands may commence arbitration.</span></span></p>


<h2><span style="font-size:18pt"><span style="font-family:&quot;Times New Roman&quot;,serif"><strong>Binding Arbitration</strong></span></span></h2>

<p><span style="font-size:12pt"><span style="font-family:&quot;Times New Roman&quot;,serif">If you and National Aero Stands don&acirc;&euro;&trade;t resolve any dispute by informal negotiation, any other effort to resolve the dispute will be conducted exclusively by binding arbitration as described in this section. You are giving up the right to litigate (or participate in as a party or class member) all disputes in court before a judge or jury. The dispute shall be settled by binding arbitration in accordance with the commercial arbitration rules of the American Arbitration Association. Either party may seek any interim or preliminary injunctive relief from any court of competent jurisdiction, as necessary to protect the party&acirc;&euro;&trade;s rights or property pending the completion of arbitration. Any and all legal, accounting, and other costs, fees, and expenses incurred by the prevailing party shall be borne by the non-prevailing party.</span></span></p>


<h2><span style="font-size:18pt"><span style="font-family:&quot;Times New Roman&quot;,serif"><strong>Submissions and Privacy</strong></span></span></h2>

<p><span style="font-size:12pt"><span style="font-family:&quot;Times New Roman&quot;,serif">In the event that you submit or post any ideas, creative suggestions, designs, photographs, information, advertisements, data or proposals, including ideas for new or improved products, services, features, technologies or promotions, you expressly agree that such submissions will automatically be treated as non-confidential and non-proprietary and will become the sole property of National Aero Stands without any compensation or credit to you whatsoever. National Aero Stands and its affiliates shall have no obligations with respect to such submissions or posts and may use the ideas contained in such submissions or posts for any purposes in any medium in perpetuity, including, but not limited to, developing, manufacturing, and marketing products and services using such ideas.</span></span></p>


<h2><span style="font-size:18pt"><span style="font-family:&quot;Times New Roman&quot;,serif"><strong>Promotions</strong></span></span></h2>

<p><span style="font-size:12pt"><span style="font-family:&quot;Times New Roman&quot;,serif">National Aero Stands may, from time to time, include contests, promotions, sweepstakes, or other activities (&acirc;&euro;&oelig;Promotions&acirc;&euro;) that require you to submit material or information concerning yourself. Please note that all Promotions may be governed by separate rules that may contain certain eligibility requirements, such as restrictions as to age and geographic location. You are responsible to read all Promotions rules to determine whether or not you are eligible to participate. If you enter any Promotion, you agree to abide by and to comply with all Promotions Rules.</span></span></p>

<p><span style="font-size:12pt"><span style="font-family:&quot;Times New Roman&quot;,serif">Additional terms and conditions may apply to purchases of goods or services on or through the Services, which terms and conditions are made a part of this Agreement by this reference.</span></span></p>


<h2><span style="font-size:18pt"><span style="font-family:&quot;Times New Roman&quot;,serif"><strong>Typographical Errors</strong></span></span></h2>

<p><span style="font-size:12pt"><span style="font-family:&quot;Times New Roman&quot;,serif">In the event a product and/or service is listed at an incorrect price or with incorrect information due to typographical error, we shall have the right to refuse or cancel any orders placed for the product and/or service listed at the incorrect price. We shall have the right to refuse or cancel any such order whether or not the order has been confirmed and your credit card charged. If your credit card has already been charged for the purchase and your order is canceled, we shall immediately issue a credit to your credit card account or other payment account in the amount of the charge.</span></span></p>


<h2><span style="font-size:18pt"><span style="font-family:&quot;Times New Roman&quot;,serif"><strong>Miscellaneous</strong></span></span></h2>

<p><span style="font-size:12pt"><span style="font-family:&quot;Times New Roman&quot;,serif">If for any reason a court of competent jurisdiction finds any provision or portion of these Terms &amp; Conditions to be unenforceable, the remainder of these Terms &amp; Conditions will continue in full force and effect. Any waiver of any provision of these Terms &amp; Conditions will be effective only if in writing and signed by an authorized representative of National Aero Stands. National Aero Stands will be entitled to injunctive or other equitable relief (without the obligations of posting any bond or surety) in the event of any breach or anticipatory breach by you. National Aero Stands operates and controls the National Aero Stands Service from its offices in United States. The Service is not intended for distribution to or use by any person or entity in any jurisdiction or country where such distribution or use would be contrary to law or regulation. Accordingly, those persons who choose to access the National Aero Stands Service from other locations do so on their own initiative and are solely responsible for compliance with local laws, if and to the extent local laws are applicable. These Terms &amp; Conditions (which include and incorporate the National Aero Stands Privacy Policy) contains the entire understanding, and supersedes all prior understandings, between you and National Aero Stands concerning its subject matter, and cannot be changed or modified by you. The section headings used in this Agreement are for convenience only and will not be given any legal import.</span></span></p>


<h2><span style="font-size:18pt"><span style="font-family:&quot;Times New Roman&quot;,serif"><strong>Disclaimer</strong></span></span></h2>

<p><span style="font-size:12pt"><span style="font-family:&quot;Times New Roman&quot;,serif">National Aero Stands is not responsible for any content, code or any other imprecision.</span></span></p>


<p><span style="font-size:12pt"><span style="font-family:&quot;Times New Roman&quot;,serif">National Aero Stands does not provide warranties or guarantees.</span></span></p>


<p><span style="font-size:12pt"><span style="font-family:&quot;Times New Roman&quot;,serif">In no event shall National Aero Stands be liable for any special, direct, indirect, consequential, or incidental damages or any damages whatsoever, whether in an action of contract, negligence or other tort, arising out of or in connection with the use of the Service or the contents of the Service. The Company reserves the right to make additions, deletions, or modifications to the contents on the Service at any time without prior notice.</span></span></p>


<p><span style="font-size:12pt"><span style="font-family:&quot;Times New Roman&quot;,serif">The National Aero Stands Service and its contents are provided &quot;as is&quot; and &quot;as available&quot; without any warranty or representations of any kind, whether express or implied. National Aero Stands is a distributor and not a publisher of the content supplied by third parties; as such, National Aero Stands exercises no editorial control over such content and makes no warranty or representation as to the accuracy, reliability or currency of any information, content, service or merchandise provided through or accessible via the National Aero Stands Service. Without limiting the foregoing, National Aero Stands specifically disclaims all warranties and representations in any content transmitted on or in connection with the National Aero Stands Service or on sites that may appear as links on the National Aero Stands Service, or in the products provided as a part of, or otherwise in connection with, the National Aero Stands Service, including without limitation any warranties of merchantability, fitness for a particular purpose or non-infringement of third party rights. No oral advice or written information given by National Aero Stands or any of its affiliates, employees, officers, directors, agents, or the like will create a warranty. Price and availability information is subject to change without notice. Without limiting the foregoing, National Aero Stands does not warrant that the National Aero Stands Service will be uninterrupted, uncorrupted, timely, or error-free.</span></span></p>


<h2><span style="font-size:18pt"><span style="font-family:&quot;Times New Roman&quot;,serif"><strong>Contact Us</strong></span></span></h2>

<p><span style="font-size:12pt"><span style="font-family:&quot;Times New Roman&quot;,serif">Don&#39;t hesitate to contact us if you have any questions.</span></span></p>


<ul>
	<li><span style="font-size:12pt"><span style="font-family:&quot;Times New Roman&quot;,serif">Via Email: <a href="mailto:lease@stands.aero.com">lease@stands.aero.com</a></span></span></li>
</ul>


""";
  @override
  Widget build(BuildContext context) {
    return Container(
      width: double.infinity,
      decoration: BoxDecoration(
        image: DecorationImage(
          image: AssetImage("assets/slicing/Untitled-46.jpg"),
          fit: BoxFit.cover,
        ),
      ),
      child: Scaffold(
        backgroundColor: Colors.transparent,
        appBar: AppBar(
          automaticallyImplyLeading: false,
          backgroundColor: Colors.transparent,
          elevation: 0,
          centerTitle: true,
          leading: GestureDetector(
            behavior: HitTestBehavior.translucent,
            onTap: () {
              Navigator.pop(context);
              // _key.currentState!.openDrawer();
            },
            child: Padding(
              padding: const EdgeInsets.all(15),
              child: Container(
                  width: 25,
                  child: Image.asset(
                    'assets/slicing/Untitled-3.png',
                  )),
            ),
          ),
          title: Row(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              Text(
                'Terms & Condition',
                style: TextStyle(color: Colors.black),
              ),
              Container(
                  width: 40,
                  height: 40,
                  child: Image.asset('assets/slicing/Untitled-4.png',
                      fit: BoxFit.cover)),
            ],
          ),
        ),
        body: Container(
          width: double.infinity,
          child: SingleChildScrollView(
            child: Padding(
              padding: const EdgeInsets.all(25.0),
              child: Container(
                decoration: BoxDecoration(
                    color: Colors.white,
                    borderRadius: BorderRadius.all(Radius.circular(20))),
                child: Column(
                  children: [
                    SingleChildScrollView(
                      child: Container(
                        child: Padding(
                          padding: const EdgeInsets.all(15.0),
                          child: Html(data: htmlData),
                        ),
                      ),
                    ),
                  ],
                ),
              ),
            ),
          ),
        ),
      ),
    );
  }
}
